### ISSUE TITLE
03 - 02 - Rhythm's gonna get you - ERD

### ISSUE THREAD

**Issue by drygwelski2020** [drygwelski2020/assignments#10]
# Rhythm's gonna get you - ERD

For this project, we will model and create a database. We are starting a record
label company, and we a place to store our bands, albums, and eventually songs.
You are creating a console app that stores our information in a database.

## Objectives

- Practice creating an Entity Relationship Diagram
- Practice working with SQL

## Requirements

Create the ERD (Entity Relationship Diagram) and resulting tables that allows a
user to store and manage the company's bands, albums, and (eventually) songs.

## How to turn in this assignment.

1. If you draw your ERD on paper, attach a photo. If you draw your ERD in a software tool, attach a screenshot of the image.
2. Paste all the SQL you wrote to create tables, insert rows, and try out SELECT/JOIN statements as a comment to this assignment.

### Explorer Mode

- [ ] Create an ERD for `Albums`, and `Bands`. They should have the following properties, use your best judgment for types.

  - [ ] Album

    - Id
    - Title
    - IsExplicit
    - ReleaseDate

  - [ ] Band

    - Id
    - Name
    - CountryOfOrigin
    - NumberOfMembers
    - Website
    - Style
    - IsSigned
    - ContactName
    - ContactPhoneNumber

  - Add ERD relationships that show:

    - [ ] One Band has many Albums

  - Create SQL statements that:
    - [ ] Add a new band
    - [ ] View all the bands
    - [ ] Add an album for a band
    - [ ] Let a band go (update isSigned to false)
    - [ ] Resign a band (update isSigned to true)
    - [ ] Given a band name, view all their albums
    - [ ] View all albums ordered by ReleaseDate
    - [ ] View all bands that are signed
    - [ ] View all bands that are not signed

# ALTERNATIVES

- If you do not wish to take on Band + Album you may go back to any of these assignments with an equivalent effort:
  - First Bank of Suncoast - Generate an ERD that supports multiple Users. Users have "Name", "Address", "Phone Number" - There will also be Transactions, each transaction will have a type (Deposit or Withdraw) and an account Checking or Savings. Generate the ERD and demonstrate SQL to create the tables, insert users, make transactions for users.
  - Jurassic Park - Generate an ERD that supports the existing Dino as well as an entity for Enclosures. The Enclosure should keep track of its Name, Capacity (number of Dinos), Location in the park. The Dinos should be able to be assigned to an enclosure. Generate the ERD and demonstrate SQL to create the tables, insert enclosures, insert Dinos, transfer dinos from one enclosure to another.

**Comment by drygwelski2020** [comment]
![ERD_Band_Album_Song](https://user-images.githubusercontent.com/56703222/83356068-77642c00-a331-11ea-8df8-251e9af1ee34.PNG)

CREATE TABLE "Band" ("Id" SERIAL PRIMARY KEY, "Name" TEXT, "CountryOfOrigin" TEXT, "NumberOfMembers" INT, "Website" TEXT, "Style" TEXT, "Is
 Signed" BOOLEAN, "ContactName" TEXT, "ContactPhoneNumber" TEXT);

CREATE TABLE "Album" ("Id" SERIAL PRIMARY KEY, "Title" TEXT, "IsExplicit" BOOLEAN, "ReleaseDate" DATE);

CREATE TABLE "Song" ("Id" SERIAL PRIMARY KEY, "Title" TEXT, "BandId" INT NULL REFERENCES "Band" ("Id"), "AlbumId" INT NULL REFERENCES "Album" ("Id"));

INSERT INTO "Band" ("Name", "CountryOfOrigin", "NumberOfMembers", "Website", "Style", "IsSigned", "ContactName", "ContactPhoneNumber") VALU
 ES ('The Beatles', 'United Kingdom', 4, 'www.thebeatles.com', 'Rock', 'Yes', 'George Martin', '111-222-3333');

SELECT * FROM "Band";

INSERT INTO "Album" ("Title", "IsExplicit", "ReleaseDate") VALUES ('Rubber Soul', 'No', '12-03-1965');

UPDATE "Band" SET "IsSigned" = 'No' WHERE "Name" = 'The Beatles';
UPDATE "Band" SET "IsSigned" = 'Yes' WHERE "Name" = 'The Beatles';
SELECT "Album"."Title" FROM "Album" INNER JOIN "Band" ON ("Name" = 'The Beatles');
SELECT * FROM "Album" ORDER BY "ReleaseDate";
SELECT * FROM "Band" WHERE "IsSigned" = true;
SELECT * FROM "Band" WHERE "IsSigned" = false;

**Comment by drygwelski2020** [comment]
![image](https://user-images.githubusercontent.com/56703222/83358210-f95b5180-a33f-11ea-85c6-94dcbef9d6ba.png)

CREATE TABLE "Band" ("Id" SERIAL PRIMARY KEY, "Name" TEXT, "CountryOfOrigin" TEXT, "NumberOfMembers" INT, "Website" TEXT, "Style" TEXT, "Is
 Signed" BOOLEAN, "ContactName" TEXT, "ContactPhoneNumber" TEXT);

CREATE TABLE "Album" ("Id" SERIAL PRIMARY KEY, "Title" TEXT, "IsExplicit" BOOLEAN, "ReleaseDate" DATE, "BandId" INT NULL REFERENCES "Band" ("Id"));

CREATE TABLE "Song" ("Id" SERIAL PRIMARY KEY, "Title" TEXT, "BandId" INT NULL REFERENCES "Band" ("Id"), "AlbumId" INT NULL REFERENCES "Album" ("Id"));

INSERT INTO "Band" ("Name", "CountryOfOrigin", "NumberOfMembers", "Website", "Style", "IsSigned", "ContactName", "ContactPhoneNumber") VALU
 ES ('The Beatles', 'United Kingdom', 4, 'www.thebeatles.com', 'Rock', 'Yes', 'George Martin', '111-222-3333');

SELECT * FROM "Band";
INSERT INTO "Album" ("Title", "IsExplicit", "ReleaseDate") VALUES ('Rubber Soul', 'No', '12-03-1965');
UPDATE "Band" SET "IsSigned" = 'No' WHERE "Name" = 'The Beatles';
UPDATE "Band" SET "IsSigned" = 'Yes' WHERE "Name" = 'The Beatles';
SELECT "Album"."Title" FROM "Album" INNER JOIN "Band" ON ("Name" = 'The Beatles');
SELECT * FROM "Album" ORDER BY "ReleaseDate";
SELECT * FROM "Band" WHERE "IsSigned" = true;
SELECT * FROM "Band" WHERE "IsSigned" = false;

**Comment by gstark** [comment]
Nicely done!

This looks great except for the ERD link between Band and Song. You don't really need that since you can determine the band by going _through_ the album. It doesn't hurt anything but it is an additional foreign key you may not need.

**Comment by drygwelski2020** [comment]
Your homework **03 - 02 - Rhythm's gonna get you - ERD** was marked: **Exceeds Expectations**
![Woah](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d5eae07a7d338c96b9a2cc704bc5ec7f53d072c/woah.gif)
> &ldquo;Woah&rdquo;
