### ISSUE TITLE
02 - 02 C# Iteration - Working with LINQ

### ISSUE THREAD

**Issue by drygwelski2020** [drygwelski2020/assignments#5]
Learning programming takes practice and the best practice is repetition. This
exercise will allow you time to work on the basics of .NET and how to apply that
logic to solving problems.

## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of iteration/enumeration

## Instructions

1. Fork [this repository](https://github.com/suncoast-devs/net-iteration) to
   your own account.
2. Change into your projects directory:
3. Clone your repository:
   `git clone https://github.com/YOUR_NAME_HERE/net-iteration`
4. Change into your project's directory: `cd net-iteration`
5. Install the dependencies: `dotnet restore`
6. Open in your editor: `code .`
7. Start the test runner: `dotnet watch test`
8. Open `Iterations.cs` and work on functions until the test passes. Once you
   are done with a test you can move to the next one by removing the
   `(Skip = "Remove to run test")` from the `Fact` attribute. There are a total
   of 10 questions.
9. Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

## Explorer Mode

- All tests passing
- No linter warnings
- Turn in the homework using the URL to your repository on GitHub.

## Additional Resources

Reference the documentation to find what kind of helpful functions
might already be in C#.

- [String Functions](https://www.c-sharpcorner.com/blogs/some-string-functions-of-c-sharp).
- [Official LINQ](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/linq/)

**Comment by drygwelski2020** [comment]
I am still trying to solve problems #3 and #6:
https://github.com/drygwelski2020/Net_Iternations

**Comment by drygwelski2020** [comment]
Your homework **02 - 02 C# Iteration - Working with LINQ** was marked: **Unacceptable**

![I'm just gonna...](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBIZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--354ad6ba2ab2a53888555f9ec77d2db94e87586c/nope.gif)
> &ldquo;I'm just gonna...&rdquo;
__&mdash; via **[Katherine Trammell](https://gifs.suncoast.io/venerations/20)**__

**Comment by gstark** [comment]
This doesn't seem like the correct repository since I don't see the code I expect to see.

**Comment by drygwelski2020** [comment]
I believe the following is the correct repository. I completed my work within the file called Iterations.cs:

https://github.com/drygwelski2020/net-iteration

**Comment by drygwelski2020** [comment]
Your homework **02 - 02 C# Iteration - Working with LINQ** was marked: **Meets Expectations**
![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBXQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e11f1f3541d668540d195fe7adcb68fd773344b8/giphy-12.gif)
> &ldquo;Well done!&rdquo;

**Comment by gstark** [comment]
Great work.

You can implement [this](https://github.com/drygwelski2020/net-iteration/blob/master/Iterations.cs#L54-L58) without using `foreach`

This is a good homework to come back to later in the cohort and use as practice.
